### PR TITLE
Enable TLS in hyperlinks

### PR DESCRIPTION
**Pull request by JeremyRand**

### CODE REVIEW

**Comment by JeremyRand** [comment]
@domob1812 Any chance you could review this?

**Comment by JeremyRand** [comment]
Fixed merge conflict.

**Comment by JeremyRand** [comment]
@jonasbits Any chance you could review this?

**Comment by JeremyRand** [comment]
@midnightmagic Any chance you could review this?

**Comment by domob1812** [comment]
ACK 765fb8a091421e9aaadc6d41c68ba6101d9dd9a2

**Review by midnightmagic — APPROVED** [review]
Looks good for this section; thanks.

**Review by jonasbits — APPROVED** [review]
ACK

**Pull request merged**
