### PR TITLE
SVG coin: fix dimensions and zoom

### PR DESCRIPTION
**Pull request by JeremyRand**
I don't have Inkscape installed at the moment, so I wasn't able to apply this change to the PNG and EPS versions.  Someone else is welcome to submit a PR for that, or else I'll do it when I get Inkscape installed on my Talos.

### CODE REVIEW

**Comment by JeremyRand** [comment]
@hlandau Any chance you could review this?

**Comment by JeremyRand** [comment]
@jonasbits Any chance you could review this?

**Comment by JeremyRand** [comment]
@midnightmagic Any chance you could review this?

**Comment by JeremyRand** [comment]
@cassiniNMC Any chance you could review this?

**Review by midnightmagic — APPROVED** [review]
Looks good. Zooms nicely.

**Comment by jonasbits** [comment]
http://wiki.inkscape.org/wiki/index.php/Release_notes/0.92#Important_changes
when openings this file in
inkscape 0.92 it warns about changes from 90 DPI to 96 DPI

**Comment by JeremyRand** [comment]
> http://wiki.inkscape.org/wiki/index.php/Release_notes/0.92#Important_changes
> when openings this file in
> inkscape 0.92 it warns about changes from 90 DPI to 96 DPI

@jonasbits Not sure I follow, are you saying there's a problem with this PR, or something else?

**Comment by JeremyRand** [comment]
Merging.

**Pull request merged**
