### PR TITLE
Remove Pantone reference

### PR DESCRIPTION
**Pull request by JeremyRand**
See https://www.linux.com/news/pantone-and-free-software and previous discussion at https://github.com/namecoin/namecoin-graphics/pull/2#issuecomment-383585922

### CODE REVIEW

**Comment by JeremyRand** [comment]
@hlandau Any chance you could review this?

**Comment by JeremyRand** [comment]
Fixed merge conflict.

**Comment by JeremyRand** [comment]
@jonasbits Any chance you could review this?

**Comment by JeremyRand** [comment]
@domob1812 Any chance you could review this?

**Comment by domob1812** [comment]
ACK 88b1a6392290c7fc997e264bec336a56fba293df

**Review by jonasbits — APPROVED** [review]
ACK hex values

**Pull request merged**
